### ISSUE TITLE
'Stop Phrase' feature with a unique phrase like "Stop Text To Speech" so that it never falsely triggers

### ISSUE THREAD

**Issue by Yzrsah** [C-Nedelcu/talk-to-chatgpt#10]
It would be very helpful if you could set a 'Stop Phrase' and 'Pause Phrase' that could stop/pause the bot while it is speaking.

The purpose of this feature is to make sure the bot does not say these words itself. By setting a 'Stop Phrase' you could ensure that the bot does not say these words itself, so that no users will consider it as a problematic bug.

I.e. by default the Pause Phrase could be set to something like "Pause Text To Speech", which is something that would be too rare for the bot to say.

**Comment by bartman081523** [comment]
#13
