### ISSUE TITLE
Support for Firefox Browser 

### ISSUE THREAD

**Issue by seedlord** [C-Nedelcu/talk-to-chatgpt#102]
I tried the legacy version in Firefox console and it works not as expected. it will read 1 message if I execute it twice.

**Comment by C-Nedelcu** [comment]
Hello seedlord,

we cannot currently support this extension for Firefox as it doesn't support the required APIs.
Once Firefox implements the necessary APIs, I would love to get to it and make a proper Firefox extension :)
