### ISSUE TITLE
Improve naming in google web store

### ISSUE THREAD

**Issue by Ewal11** [C-Nedelcu/talk-to-chatgpt#104]
Searching the addon as "talk to chatgdp" does show the addon
Searching the addon as "talk-to-chatgdp" does not show the addon

I only got it to show by case sensitive search "Talk-to-ChatGPT" 

I'm not sure if this is a naming issue or this is related to the naming it self.

**Comment by C-Nedelcu** [comment]
Hi Ewal11,
thank you for your suggestions. I'm not sure what could be done.
At least on Google it's easy to find:
![image](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/4685072/50b8cd05-c635-4563-97c7-15e0777a8b35)
Beyond that... Maybe google's web store search algorithms are wonky? hopefully they can revise that. There is not much I can do...
