### ISSUE TITLE
Text Reader No Longer Works

### ISSUE THREAD

**Issue by highlypersuasive** [C-Nedelcu/talk-to-chatgpt#105]
Everything else is fine however text to speech is not working for me. I've tried different voices but can't get it to start again. Any recommendations? 

Thanks

**Comment by highlypersuasive** [comment]
this was a conflict with superpowergpt extension - once i disabled it's working again

**Comment by C-Nedelcu** [comment]
thanks for letting me know, conflicts with other extensions could indeed explain a lot of unexpected behaviors
