### ISSUE TITLE
"Chat-gpt says" issue

### ISSUE THREAD

**Issue by mikey005** [C-Nedelcu/talk-to-chatgpt#106]
how can I remove this, it is very annoying, can someone help?
![chat-gpt](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/119559705/83ae46f4-5246-4572-8c1f-8e947b96f46f)

**Comment by C-Nedelcu** [comment]
hi,
this is caused by another extension you are using (such as AIPRM) you can disable other extensions temporarily while you use Talk to ChatGPT.
I think this is a duplicate of #75

**Comment by mikey005** [comment]
help @C-Nedelcu

**Comment by mikey005** [comment]
ok, then there is no solution except removing the continue button for which I should buy the premium AIPRM.
