### ISSUE TITLE
Similar plugin for character.ai

### ISSUE THREAD

**Issue by BlueTechRS** [C-Nedelcu/talk-to-chatgpt#107]
Hi,

I'm new when it comes to posting to github, and i just revived this account simply to leave this message. My apolgies if this message is not in the right place, or anything else that might not be in order.

Would such a plugin like this be possible for character.ai as well? Mainly something that is able to autonomously flow conversations without physical input like this plugin does beautifully. Character.ai already has voice support, but autonomously submitting messages is something it really lacks. I'm looking to integrate character.ai into my car, and the simple fact that i have to press a button to send the message kind-of ruins it all, and makes it unsafe to use. I've tried doing this for ChatGPT, and while ChatGPT is a phenomenal masterpiece of technology, the way ChatGPT responds to things in a car-scenario is simply too bland for me. character.ai and the way it allows you to customize 'your' AI completely solves that problem.

I would have made such a plugin myself if i could, but i'n not too proficient with code at all. 10 lines of code made by me will create 11 errors.
Therefore, thought i would drop the idea here. A shot not taken is a shot always missed.

Kind regards,

BTRS

**Comment by C-Nedelcu** [comment]
Hi there,

Thank you for coming here and your post totally has its place here.

However I'm afraid I may not have the answer you're looking for. Talk-to-chatGPT is an extension that is very specifically tailored to work in the ChatGPT UI. Having it work on another site would be rewriting pretty much from scratch, or maybe rewriting half of it.

The easiest way to achieve what you are looking for is to create a new extension (maybe one that re-uses some of my code? I mean, this is an open source project, so why not?) However I'm afraid I wouldn't have the time to dedicate to managing a second extension in addition to my current work and family duties.

Hopefully someone else picks up the idea and gets it done, this sure would be fun!
