### ISSUE TITLE
It can speak, but it doesn't record my voice

### ISSUE THREAD

**Issue by MSofEU** [C-Nedelcu/talk-to-chatgpt#110]
Can someone tell me how to trigger the recording function. I installed the extension on Microsoft Edge. It can speak, but it can't listen. I've tried automatic sending and manual sending. I have checked my microphone which is on. My microphone can work in other apps. That red bar just doesn't move.

**Comment by C-Nedelcu** [comment]
Hello,

Have you allowed the extension permission to use the microphone?
would you consider trying it on Google Chrome?

This function is particularly simple and very few people have issues with it. It's likely a configuration issue on your end.
If you really have trouble getting things to work, I suggest you send me the log from the javascript console, so I could take a look and maybe offer directions?
