### ISSUE TITLE
multiple languages

### ISSUE THREAD

**Issue by veritaism** [C-Nedelcu/talk-to-chatgpt#111]
hi there, great project. 
however, when learning a language and using a mix of languages as input, it won't be able to follow.
I admit that one is tricky, but just to mention it.

**Comment by C-Nedelcu** [comment]
Thanks for the input.

I am working on an "interpreter mode" that would mix languages.

If this meets success, I could consider other "modes" like language learning or something.

**Comment by veritaism** [comment]
Sounds great. Will check once available.
In general, the one request, one response flow is a bit mechanic. People also interfere with each other if an answer is not on point or off topic. That would also greatly improve a conversation.
