### ISSUE TITLE
Use voices on computer?

### ISSUE THREAD

**Issue by Cblu2th** [C-Nedelcu/talk-to-chatgpt#112]
Is there any method you could implement that would allow SAPI voices already installed on the computer to be used? I know that there are other options already available along with the API but this would make things nicer and more customizable.

**Comment by C-Nedelcu** [comment]
Hello,

this extension does use the regular browser's text to speech API 
Chrome's TTS API uses SAPI https://developer.chrome.com/docs/extensions/reference/tts/ from what I'm reading here.

In addition to this, we support ElevenLabs which is a third party API with amazing voices (and you can even create your own custom voices).

I am open to integrating more TTS APIs if given pointers/directions, as long as they're javascript based, I'm all in.
