### ISSUE TITLE
if you do will this,it will work in PC and mobile brower

### ISSUE THREAD

**Issue by joe12801** [C-Nedelcu/talk-to-chatgpt#123]
https://xqdoo00o.github.io/chatgpt-web/?1685474780778

this web chatgpt can work in PC brower and mobile brower

You can refer to this webchat chatgpt to change your plug-in so that it can be used on mobile phones,Whether it's an Android phone or an iPhone
https://github.com/xqdoo00o/chatgpt-web

**Comment by C-Nedelcu** [comment]
Hello,
I am not sure I understand what you would like me to do with this ?
thanks in advance for your kind explanations

**Comment by nyngwang** [comment]
@C-Nedelcu You can just close this. He is trying to promote his own app.
