### ISSUE TITLE
Raspberry pi 4B buster OS - chromium 

### ISSUE THREAD

**Issue by PCBot-Lab** [C-Nedelcu/talk-to-chatgpt#125]
Hi,

talk-to-chatgpt speech-to-text works good 

I'd like to know if text-to-speech using ElevenLabs API can works. 

"Invalid settings values. TypeError: Cannot read property 'lang' of undefined"

Thanks

**Comment by C-Nedelcu** [comment]
Hello,

yes, it's supposed to work. I am assuming there is a bug somewhere.

Could you send me a screenshot of this window here:
![image](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/4685072/7039a8a4-836c-440a-a1f7-91f2212e13b3)

Two screenshots in fact, one with the Elevenlabs option enabled, and one with it disabled.
This should help me understand and hopefully come up with a fix.

**Comment by PCBot-Lab** [comment]
Greetings from Atlanta,

It is not possible to select AI voice and language.
I am using RPi Rasbian 10 (32 bit)
I will try RPi Rasbian 11 (32 bit  and 64 bit)

![Chromium](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/119534764/a45a5740-44ee-4f60-947e-ad4272032d26)
![settings 1](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/119534764/2c59a9f4-e88f-44ca-ae14-890f3d107efa)
![ElevenLabs](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/119534764/3ceeb473-71ad-4082-834a-1ffb14c73ab7)






Thanks

**Comment by C-Nedelcu** [comment]
hello,

Thank you for your feedback.
I've released a new version, v2.6.1, which fixes this. 

I recommend doing a manual install for now (instructions are on the project home page)
Or else, simply wait until the update is approved on the Chrome store. From my estimate, it should be on Tuesday or Wednesday.

**Comment by PCBot-Lab** [comment]
Hi C-Nedelcu,

Thank you so much for your support

PCBot

**Comment by C-Nedelcu** [comment]
v2.6.1 is live on Chrome extension store. 

If you want to give it a try, could you confirm that this fixes your issue?

**Comment by C-Nedelcu** [comment]
Excellent, muy bien!
Glad it's working well for you!

If you haven't already, I'd appreciate a positive review on Chrome or Edge store ;-) Cheers
