### ISSUE TITLE
QUESTION: Have you considered adding support for Tortoise-TTS as voice backend?

### ISSUE THREAD

**Issue by hradec** [C-Nedelcu/talk-to-chatgpt#126]
Just wondering. ElevenLabs is great, but the free tier is quite limited, and I wouldn't pay 5$ bucks a month for just 3X what I get in the free tier. 

Considering [Tortoise-TTS](https://github.com/neonbjb/tortoise-tts) sounds sooooooo good and its open source (so unlimited talking!), I wonder if you considered supporting it as a backend.

**Comment by C-Nedelcu** [comment]
Hello,
this would be interesting, but as far as I know, there isn't a javascript API available for it.
It's a Python project exclusively, which means your web browser cannot run it.
Hence it isn't compatible with a browser extension (which are javascript only)
