### ISSUE TITLE
Doesn't automatically send message in ChatGPT

### ISSUE THREAD

**Issue by FutureMosaic** [C-Nedelcu/talk-to-chatgpt#127]
Is this affecting anyone else? I have done all the troubleshooting, but messages won't send automatically or by voice command

**Comment by tinchoforever** [comment]
Same

**Comment by 7k50** [comment]
Yes. I'm thinking perhaps ChatGPT has changed the design of their send button?

**Comment by mikekylo** [comment]
Sending either automatically nor manual stopped working

**Comment by Rndiaz01** [comment]
same problem here

**Comment by C-Nedelcu** [comment]
hello,

Thank you for your feedback.
I've released a new version, v2.6.1, which fixes this. 

I recommend doing a manual install for now (instructions are on the project home page)
Or else, simply wait until the update is approved on the Chrome store. From my estimate, it should be on Tuesday or Wednesday.

**Comment by C-Nedelcu** [comment]
v2.6.1 is live on Chrome extension store. Confirmed fixing the issue
