### ISSUE TITLE
Prompt not sent when I stop talking with Automatic send checked

### ISSUE THREAD

**Issue by itorres008** [C-Nedelcu/talk-to-chatgpt#128]
Hello.
I have just installed the plugin. Seems like a great idea. 
On settings I have the "Automatic send" option checked. So, I expect my prompt to be sent when I stop talking. What I see happening is: 
- Voice prompt recognized and written on the Send a message textbox after I stop talking. 
- the Send Icon on the right, usually green turns to a pink color - the message is not sent 
- I click on the pink button, the button doesn't react to click and doesn't send the message
- Only way I've found to send is pressing Enter twice. The first time, cursor drops to next line, the Icon turns green but message is still not sent. On second time pressing Enter the message is sent. Then answer comes back and is read correctly. 
Am I missing something about the Automatic Send function? 

I have also tried unchecking "Automatic send" option to try sending by saying "Send Message Now" (I actually changed it to "Send Now"). 
What happens is that after I stop speaking the Icon turns pink like before, the Red Icon on the Chrome Tab above is still showing microphone is active. 
I say "Send Now", the red microphone icon goes away, apparently signaling that it successfully recognized the "Send Now" phrase. However, the message is still not sent as before.
In general, it seems the message is not sent either automatically when I stop talking or if I activate the "Send Now" command.
Message is only sent if I hit Enter twice. 

Thanks.

**Comment by improveTheWorld** [comment]
It's related to Chatgpt html page that seems to be changed by OpenAI. It seems Open AI wants to force developers to use the GPT API, which is fee charged, instead of the free chatgpt access !

**Comment by C-Nedelcu** [comment]
hello,

Thank you for your feedback.
I've released a new version, v2.6.1, which fixes this. 

I recommend doing a manual install for now (instructions are on the project home page)
Or else, simply wait until the update is approved on the Chrome store. From my estimate, it should be on Tuesday or Wednesday.

**Comment by C-Nedelcu** [comment]
v2.6.1 is live on Chrome extension store. Confirmed fixing the issue

**Comment by itorres008** [comment]
Thanks. It updated automatically. Tried it just now and seems working OK. 👍
