### ISSUE TITLE
problem with automatic sending of the spoken message, changes in the chatgpt send button.

### ISSUE THREAD

**Issue by enrix507** [C-Nedelcu/talk-to-chatgpt#129]
Hello friend, first of all thank you very much for the talkgptchat application, it is too good, I use it for a lot of interaction with chatgpt, I would like to comment on an error that lately is affecting the automatic sending of the spoken message, in the application it seems that the button that is on the platform they changed its color, I imagine that this is affecting the previous code with the old button, since the messages are not sent until I press the enter button, causing the automatic message to not be sent, I appreciate your help, greetings and blessings.

**Comment by tinchoforever** [comment]
Same here.

**Comment by mattkuppers** [comment]
When will the issue be fixed? I need to study for an exam! Many thanks!

**Comment by pablomiyashita** [comment]
I have the same problem, when i speak the button is purple only when i manually copy this symbol " ˘ " the button changes to green and it is automatic.

**Comment by tadeogutierrez** [comment]
Same here. Seems that the "disabled" set tu false on sendMessage is not working now.

**Comment by Rndiaz01** [comment]
Same problem here. Waiting for a solution. thank you.

**Comment by C-Nedelcu** [comment]
hello,

Thank you for your feedback.
I've released a new version, v2.6.1, which fixes this. 

I recommend doing a manual install for now (instructions are on the project home page)
Or else, simply wait until the update is approved on the Chrome store. From my estimate, it should be on Tuesday or Wednesday.

**Comment by C-Nedelcu** [comment]
v2.6.1 is live on Chrome extension store. Confirmed fixing the issue

**Comment by xhabara** [comment]
> v2.6.1 is live on Chrome extension store. Confirmed fixing the issue
2.6 was great for me however the 2.6.1 including the manual install cannot recognize voice inputs anymore. looking forward to use it again. thank you so much. bless
