### ISSUE TITLE
Automatic send not working. When 'Automatic send' box unchecked 'Manual send word(s)' not working either. Please advise how to make sending work!

### ISSUE THREAD

**Issue by mikekylo** [C-Nedelcu/talk-to-chatgpt#130]

**Comment by mikekylo** [comment]
Has this been fixed now?

**Comment by C-Nedelcu** [comment]
hello,

Thank you for your feedback.
I've released a new version, v2.6.1, which fixes this. 

I recommend doing a manual install for now (instructions are on the project home page)
Or else, simply wait until the update is approved on the Chrome store. From my estimate, it should be on Tuesday or Wednesday.

**Comment by C-Nedelcu** [comment]
v2.6.1 is live on Chrome extension store.

**Comment by xhabara** [comment]
> v2.6.1 is live on Chrome extension store.
it was working fine for me with 2.6, but now with the 2.6.1 it cant detect voice input anymore but it can do the voice response with typed input. any suggestions on how to fix it?

**Comment by C-Nedelcu** [comment]
> > v2.6.1 is live on Chrome extension store.
> > it was working fine for me with 2.6, but now with the 2.6.1 it cant detect voice input anymore but it can do the voice response with typed input. any suggestions on how to fix it?

hi, can you check issue #134 ?
I will need help to understand what's going on. It's all working well on my side

**Comment by xhabara** [comment]
> > > v2.6.1 is live on Chrome extension store.
> > > it was working fine for me with 2.6, but now with the 2.6.1 it cant detect voice input anymore but it can do the voice response with typed input. any suggestions on how to fix it?
> 
> hi, can you check issue #134 ? I will need help to understand what's going on. It's all working well on my side

Thanks. it is resolved now following your suggestion. Prompt Genius is the bad guy here :))
