### ISSUE TITLE
Speech-To-Text doesnt work on Opera

### ISSUE THREAD

**Issue by kevstar0** [C-Nedelcu/talk-to-chatgpt#132]
The speech to text capability provided by the extention is not working on Opera GX

**Comment by C-Nedelcu** [comment]
Hello,
Unfortunately, this extension will not work on Opera because it doesn't support the required APIs.
The only supported browsers are Google Chrome and Microsoft Edge. 
There is not much anyone can do, other than the Opera developers properly implementing these APIs.
