### ISSUE TITLE
2.6.1 Not Adding text with Superpower ChatGPT extension installed.

### ISSUE THREAD

**Issue by workboi** [C-Nedelcu/talk-to-chatgpt#135]
Text is not being added with this extension installed.

**Comment by C-Nedelcu** [comment]
hello,

I would recommend checking the reply I made here, for another user who was using another extension who breaks things: 
https://github.com/C-Nedelcu/talk-to-chatgpt/issues/134

in short: Talk-to-chatgpt is "neutral", whereas other extensions such as the one you are using heavily modify the page DOM and can result in issues like this.
