### ISSUE TITLE
doesn't work with chinese.

### ISSUE THREAD

**Issue by werererer** [C-Nedelcu/talk-to-chatgpt#14]
It doesn't read Chinese out loud If the ai responds with chinese . Which is kind of sad because I like Chinese :).

for example:

![image](https://user-images.githubusercontent.com/42046082/210137598-29fb2633-f3d1-4103-b8a2-0eabbc07ba63.png)

will not be read out loud. I have the settings like that:

![image](https://user-images.githubusercontent.com/42046082/210137618-658a7597-11c0-45ed-a458-4364fa191b85.png)

**Comment by dev-eduka** [comment]
I will check it out, it might be due to the fact that the punctuation is different in Chinese.
If that's the case it should be an easy fix

**Comment by dev-eduka** [comment]
> I use Japanese and have had this problem as well. I hope it helps with this issue.

hi @naoya-in could you give me all the common punctuation marks in japanese?
I know the chinese ones because I can type chinese, but unfortunately I dont type japanese

**Comment by naoya-in** [comment]
hi @dev-eduka

In Japanese, `、` (`，`) and `。` (`．`) are used as punctuation marks.
The `、` (`，`) is used much like a comma, and the `。` (`．`) is used in much the same way as a period in English.
Also `！` and `？` are sometimes used in sentences with the same meaning as in English

I hope this will help.

**Comment by Taounit** [comment]
Same here, Japanese voice does not work. Only input.

**Comment by dev-eduka** [comment]
hello,
this issue should be addressed in v1.6
v1.6 is available on github, you can sideload it using developer mode
OR wait a couple of days until the update is approved and starts appearing on the Play store

**Comment by naoya-in** [comment]
This problem was resolved in Japanese. Thank you!

**Comment by C-Nedelcu** [comment]
Thanks naoya-in!

As for 中文: I was able to converse in Chinese perfectly using the settings below.

![Screenshot_1](https://user-images.githubusercontent.com/4685072/215302164-112f19fd-1573-4272-8dfb-21e06b50a5ea.png)
![Screenshot_2](https://user-images.githubusercontent.com/4685072/215302168-2b43d7b2-0618-4c36-8710-0dc87d1c94e4.png)

I am going to mark the issue as closed now.

**Comment by werererer** [comment]
![image](https://user-images.githubusercontent.com/42046082/215781384-aeba3b66-71c9-4023-848d-ffbbe33cb100.png)
User: 你会说中文吗。
GPT: 是的，我会说中文。
In this example only 我会说中文。is being read out 是的， never gets read out aloud.

**Comment by C-Nedelcu** [comment]
I encountered a similar problem before, but it turns out it was caused by my use of a particular set of speakers. Any audio would get cut off for the first second or so. They were bluetooth speakers.

When I switched to my laptop's internal speakers, it stopped happening.

Could maybe look into that?

Alternatively, look for the javascript console. if it says "Saying out loud: 是的" then it means the 是的 was definitely sent to the TTS engine. And beyond that, it's out of my control.

**Comment by C-Nedelcu** [comment]
[werererer](https://github.com/werererer)'s commit has fixed this issue.
I am releasing this as v1.6.1 and publishing to the play store.

**Comment by rjda11** [comment]
I am having no luck getting the extension to talk to me in Chinese. The browser I am using is Edge.
Here are my settings:
![TalkToChatgpt Settings](https://user-images.githubusercontent.com/130098502/230478325-a38a3aa6-bdc3-4953-9ea3-c09312cfe816.jpg)
Am I doing something wrong with the settings?
