### ISSUE TITLE
No way to set the input device

### ISSUE THREAD

**Issue by niieani** [C-Nedelcu/talk-to-chatgpt#16]
If you have multiple microphones, there's currently no way to select the input device.

**Comment by dev-eduka** [comment]
This is a setting that is defined in the web browser, not in the Chrome extension.
example tutorial: https://thenextweb.com/news/how-to-change-your-microphone-or-camera-in-chrome

**Comment by niieani** [comment]
There's an API for websites to select the device though. Google Duo/Meet for example uses it to enable selecting which microphone and camera to use.

**Comment by C-Nedelcu** [comment]
This won't be implemented. It will always use the input device you select in Google Chrome. I am closing this issue.
