### ISSUE TITLE
Extension not working at all. Any help? Chrome MacOS

### ISSUE THREAD

**Issue by aodrasa** [C-Nedelcu/talk-to-chatgpt#165]
Unsure why but can't get any speech out of the extension, both on system voices and ElevenLabs.

I'm on MacOS (14.0 Beta (23A5286i)) and Chrome (115.0.5790.170 (arm64)).

Realise this _could_ have to do with the beta I have installed but would love to fix this.

Cheers

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue?
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
