### ISSUE TITLE
prevent chatgpt from mentioning or describing emojis when she places them in her replies.

### ISSUE THREAD

**Issue by enrix507** [C-Nedelcu/talk-to-chatgpt#166]
hello friend, there is the possibility of enabling an option that prevents chatgpt from responding by describing each emoji that she places in her responses, an example in the new configuration that allows customizing the behavior of chatgpt by asking chatgpt to act happy, funny, smiling empathetic, happy, etc., chatgpt when she takes a more positive or cheerful role, she begins to use a lot of emojis, and that's fine, but the problem is that it's annoying that she is describing each emoji she puts by voice, if she puts a smile emoji It describes it as a smiling face etc etc, and so with each emoji that you place, it would be nice to have the option for chatgpt to ignore these emojis that it does not read them, to read only the text without describing the emoji to have a better interaction with it. I really appreciate your attention and help please,🙇

**Comment by C-Nedelcu** [comment]
It's a good idea.
If anyone would like to contribute to the project and implement this idea please be my guest

**Comment by PxPerfectMike** [comment]
Hello,

I've implemented the requested feature and submitted a PR for review. The PR adds functionality to detect and optionally remove emojis from the text, based on user preferences set in the settings.

PR Link: [PR #181](https://github.com/C-Nedelcu/talk-to-chatgpt/pull/181)

Looking forward to your feedback!

**Comment by C-Nedelcu** [comment]
thanks a lot Mike ! thats awesome.
I will work towards publishing v2.7.2 with your fix this weekend, and see if I can include one or two other things as well.
