### ISSUE TITLE
Suggestion for 'Automatic Send' Silent Duration

### ISSUE THREAD

**Issue by matt1006** [C-Nedelcu/talk-to-chatgpt#167]
Hello,

I am a fan of Talk to ChatGPT, and I appreciate your hard work on it!

I have a small suggestion about the “Automatic send” feature. 

The silent duration that triggers sending is a bit too short for me, and my messages often get sent incompletely before I finish speaking (My speaking speed is rather slow, and I often pause for a few seconds to create prompts).

Since speaking speed varies among users, perhaps an option to customize the silent duration might be a great addition, especially for users who need a bit more time to speak.

This is just a suggestion. For now, I am using the “Manual send words” feature, and it is working well.

I hope this feedback is helpful. Thank you again for providing such an excellent tool!

Regards,

**Comment by C-Nedelcu** [comment]
Hello,

Unfortunately, the Speech Recognition API does not support this option, as far as I know.
So what you are asking, while it would be very useful, I unfortunately simply cannot provide in Talk-to-ChatGPT :-(

I will keep it in mind though, and if it ever becomes a possibility, I will make sure to implement your suggestion.

**Comment by matt1006** [comment]
Thank you for your reply. 

I understand the constraints now, and it is alright because the “Manual send words” function serves my needs :)

I really appreciate your dedication to this wonderful tool. Keep up the great work!
