### ISSUE TITLE
UPDATE Eleven Multilingual v2

### ISSUE THREAD

**Issue by enrix5077** [C-Nedelcu/talk-to-chatgpt#168]
recently eleven labs updated its platform with a new model called Eleven Multilingual v2, but the plugin still works with the old V1, version 2 is better in every way and in all languages it gives better results improves the voices in both English and in another language and it corrects many errors of the previous versions, I would appreciate it if you please update to the new version so that the api uses the v2 version and not the old one, since it seems that when placing the api in chatgpt it continues to use the old version v1 , v2 is better. THANKS VERY MUCH.

**Comment by eiko4** [comment]
file:content.js var CN_TTS_ELEVENLABS_MODELS = {"eleven_monolingual_v2": "Multi-language (autodetect)", "eleven_multilingual_v2": "Multi-language (autodetect)"};

**Comment by enrix5077** [comment]
thank very much

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue?
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
