### ISSUE TITLE
TalkToChatGTP and ElevenLabs issue

### ISSUE THREAD

**Issue by NickDiamondsIsForever** [C-Nedelcu/talk-to-chatgpt#169]
Hi, 
When using the TalkToChat extension with ElevenLabs, I am having a serious issue with the audio playback. It's coming out clipped and choppy as different voices/samples. When I look at the "history" on ElevenLabs, i find that, instead of one chunk of text/sample, each word is being separated as its own "generated sample". 

I'm wondering why this is happening and if you can help me resolve this issue. When I use the extension within ChatGPT, i'd love for it to play back as one smooth consistent sample, the way it does within ElevenLabs. 
thanks
n

<img width="880" alt="Screen Shot 2023-08-30 at 1 32 43 PM" src="https://github.com/C-Nedelcu/talk-to-chatgpt/assets/143657107/16b64909-411f-4730-a7fe-0c385745cf4e">
<img width="894" alt="Screen Shot 2023-08-30 at 1 28 59 PM" src="https://github.com/C-Nedelcu/talk-to-chatgpt/assets/143657107/8e310f1b-efb0-49bf-8e22-1d669a59e92e">

**Comment by GuusDeKroon** [comment]
Exactly what I noticed as well- makes the audio sounds significantly worse. Hoping for this to get fixed!

**Comment by NickDiamondsIsForever** [comment]
When I first started using it, this wasn't happening, so i was assuming it's just a glitch? Has it always happened for you?

**Comment by GuusDeKroon** [comment]
Yes, for me it hasn't been any different way.

**Comment by GuusDeKroon** [comment]
It seems the " Don't use commas/semicolons/etc. to break down replies into sentences" option might fix this!

**Comment by NickDiamondsIsForever** [comment]
rats, i tried that but it didn't work :( 
i'm gonna keep digging around, let me know if you figure it out on your end! 
would be nice if ElevenLabs was reachable with this

**Comment by NickDiamondsIsForever** [comment]
oh my god no it works!!

**Comment by NickDiamondsIsForever** [comment]
Thank you so much for help. Truly

**Comment by C-Nedelcu** [comment]
Just wondering what settings do you use for Stability and Similarity?
Try different settings such as 0 for both, 
or Stability=0.1 and Similarity=1  ?

I've found that it greatly impacts the result - I think that's just how it works at ElevenLabs.

**Comment by NickDiamondsIsForever** [comment]
hey. It was set to 0 for stability and 1 for similarity. i tried moving some things around, as you suggested and it seems to change things slightly, but nothing quite fixes it. If i type the text directly into ElevenLabs it's very consistent and smooth but every sentence does tend to get chopped up into different "samples". Not sure how to correct this...

**Comment by Khorimus11** [comment]
I have the problem that, despite my settings in German, he suddenly chooses the English language mode to answer, even though it is set differently. But the history also says that he used the English model. but it should be multilingual.

**Comment by kamilo558** [comment]
I'm currently experiencing an issue with the extension. I've entered my API from Eleven Labs and selected a voice. After saving it, when I input a question via voice in ChatGPT, the corresponding answer is not being read aloud. However, when I deactivate Eleven Labs, the answer is read aloud in the default voice. Does anyone have any suggestions on what I can do to make this work with the Eleven Labs voice? Thank you.

**Comment by kamilo558** [comment]
In the second browser I get the following error message after api input "chat.openai.com says
[3] ElevenLabs API error: TypeError: Failed to execute 'decode' on
'TextDecoder': The provided value is not of type '(ArrayBuffer or
ArrayBufferView)'." Can anyone help me with this?

**Comment by C-Nedelcu** [comment]
Hi @kamilo558 
I will be making an update soon to address the ElevenLabs problem.
Thanks for your patience!

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue?
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

What I did to get it working:
- Open the Talk-to-chatGPT settings menu
- Now, the voices in the list are based off the V2 models
- I left the default settings blank for Stability and Similarity (literally no value at all. Empty box. Don't put 0!)
- It was a little better but still not perfect
- What really helped was when I selected a different voice... And also when I started using a paid subscription! I might be wrong, but it seems like under the free tier, I was getting lower quality.

**Comment by NickDiamondsIsForever** [comment]
The entire chrome extension seems to be down...Not making sounds, and appears to be a problem for everyone. Apparently there is an update that was released today but it's not showing on my chrome browser. Do you know how to fix?

**Comment by NickDiamondsIsForever** [comment]
Anyone know if the extension was removed from the chrome store and
<img width="920" alt="Screen Shot 2023-09-17 at 5 18 07 PM" src="https://github.com/C-Nedelcu/talk-to-chatgpt/assets/143657107/9fe21583-e2e7-4aff-aa02-a627799d0353">
 if it will be returning?

**Comment by C-Nedelcu** [comment]
The current version on the Chrome store was not working properly due to an update from OpenAI which disabled the ElevenLabs functionality. As a result I was getting review-bombed with 1 star reviews from frustrated users (understandably). I decided to take it down momentarily, until the newest version is approved.

Meanwhile those who still want to use the extension can install it manually (v2.7.1 as of today) installation instructions are on the project home page.

**Comment by NickDiamondsIsForever** [comment]
apologies, i didn't realize you actually wrote this extension! people are ingrates. thanks for making this!

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
