### ISSUE TITLE
reading code

### ISSUE THREAD

**Issue by bartman081523** [C-Nedelcu/talk-to-chatgpt#17]
could it be possible to detect a code block and skip reading the code blocks?

**Comment by C-Nedelcu** [comment]
I'm on the fence about this
I could implement what you are asking, but what if someone comes back and complains that the code isn't being read? 
Then I would have to have a new option in the settings. The settings menu is getting quite heavy.
I don't really consider TTGPT to be very appropriate for work, I see it as more of a fun toy or something that can help disabled people or children. What if visually impaired users want the code to be read?

**Comment by bartman081523** [comment]
Ok, I agree with you. Your arguments seem to weight heavier than my
request. Thanks for taking the time to clarify.

C-Nedelcu ***@***.***> schrieb am So., 29. Jan. 2023, 04:17:

**Comment by bartman081523** [comment]
> V2.3.0 now offers an option to skip code blocks.
> Hope you enjoy it :)

Yes.
Thank you very much.
