### ISSUE TITLE
VOICE BOT ISSUE

### ISSUE THREAD

**Issue by Spt2000** [C-Nedelcu/talk-to-chatgpt#174]
Voice bot doesn't work, it is also currently enabled. Any suggestions to fix this issue, thank you in advance!

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue? 
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
