### ISSUE TITLE
No speech input (Chrome, Win 11)

### ISSUE THREAD

**Issue by kulturfenster** [C-Nedelcu/talk-to-chatgpt#175]
Hi there

For some reason GPT doesn't listen to my voice commands. Is there any way to change the input method? Or to debug the system?

**Comment by muhammadkhafipangestu** [comment]
same problem here. I use brave browser on win 10. already allowing the requirement but the ext didn't detect my voice. showing the red bar under it. is it cause by brave browser didn't support the extentsion?

**Comment by C-Nedelcu** [comment]
> same problem here. I use brave browser on win 10. already allowing the requirement but the ext didn't detect my voice. showing the red bar under it. is it cause by brave browser didn't support the extentsion?

hello, indeed Brave does not support the voice recognition API.

@kulturfenster  : have you tried this? does it work there?
https://www.google.com/intl/en/chrome/demos/speech.html

**Comment by C-Nedelcu** [comment]
> Hi there
> 
> For some reason GPT doesn't listen to my voice commands. Is there any way to change the input method? Or to debug the system?

Could you try v2.7.0 and see if fixes your problem?

As of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

I recommend toying around with the settings to ensure it works, try with different languages.

For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by kulturfenster** [comment]
I realized that the web speech API didn't work either. So I rechecked my settings and could find the problem. My browser was trying to use an unplugged microphone. 

In my case it'd have been great to be able to choose the input. But I don't know how hard that is to implement. 

Anyway, thanks for replying and keep up the good work!
