### ISSUE TITLE
Issues with Talk-to-chatGPT Plugin and ElevenLabs API Voices

### ISSUE THREAD

**Issue by Psytorpz** [C-Nedelcu/talk-to-chatgpt#176]
Hey,

I recently encountered a problem with the Talk-to-chatGPT plugin. While the basic voices work seamlessly, I've been experiencing issues when trying to use the voices that integrate with the ElevenLabs API. Just a few days ago, everything was functioning properly.

I was in the midst of creating a video presentation for the plugin, and the issues surfaced during the recording. As you can imagine, this has been quite frustrating and somewhat embarrassing. I can't hear any response when I speak to GPT; it seems like nothing is happening.

I've triple-checked and can confirm that my API key is correct. There were no errors when inputting it into the plugin. I tried with Edge and same issue.

Has anyone else experienced this? Any insights or potential solutions would be greatly appreciated. Looking forward to getting this resolved so I can showcase this awesome plugin to my audience.

Thanks in advance!

EDIT: It seems like that ElevenLabs is processing my audio, but I can't hear anything when I'm on ChatGPT. 

![image](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/121165866/ef0e01a5-b784-436f-9470-2ac5d2b6d0f2)

**Comment by C-Nedelcu** [comment]
Hi there,
I will be making an update soon to address the ElevenLabs problem.
Thanks for your patience!

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue? 
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by Psytorpz** [comment]
Hey! Thank you so much for you work! It works with the new version now! 

Cheers,

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
