### ISSUE TITLE
No Audio Output of ElevenLabs Voices in ChatGPT with Talk-to-ChatGPT Extension

### ISSUE THREAD

**Issue by Wynndow7** [C-Nedelcu/talk-to-chatgpt#177]
I am on a PC. My talk-to-ChatGPT works fine with the default computer voice. However, when I add the ElevenLabs API Key, ChatGPT still detects my voice but only answers in text - I hear no audio. When I test the voices at elevenlabs.io, I hear them fine, just not in ChatGPT. Is this a setting issue on my computer? This happens in both Chrome and Edge. Thanks!

**Comment by jackokiwi** [comment]
I have nothing coming from my speaker in HP laptop, with either elevenlabs or default. Hears me fine and types. Have latest windows installed. Speaker works fine otherwise. Thanks, love the idea, be great to hear.

**Comment by C-Nedelcu** [comment]
hello,
I have attempted to fix this in v2.7.0
as of this message, v2.7.0 is currently pending approval on Chrome/Edge stores, but you can install it manually to try.
the manual installation method is described on the homepage.

Please let me know if v2.7.0 fixes this issue? 
For me everything works fine after hours of testing - both with browser text-to-speech and ElevenLabs

**Comment by MikeAW2010** [comment]
Hi, the extension seems to be completely removed from the Chrome store currently.

**Comment by C-Nedelcu** [comment]
v2.7.1 is now available on the Chrome store and fixes this.
I am closing the Issue, feel free to reopen in case you are still having trouble (with v2.7.1)
