### ISSUE TITLE
Speech recognition doesn't work on microsoft edge

### ISSUE THREAD

**Issue by johnmatthewtennant** [C-Nedelcu/talk-to-chatgpt#18]
I get these two errors in the console repeated infinitely
```
Error while listening
```
```
​I've stopped listening
```

I want to use microsoft edge because it has better TTS voices, which support high playback rates. The google voices sound garbled at high speeds

**Comment by dev-eduka** [comment]
Sorry, the SpeechRecognition API doesn't seem to be supported on Microsoft Edge
see here: https://caniuse.com/speech-recognition
This extension is only for Google Chrome

**Comment by bartman081523** [comment]
You can test the Speech Recognition with WebSpeech here
https://codepen.io/gregja/pen/OJbYRwa?editors=1111
