### ISSUE TITLE
Speech-to-text in multiple languages?

### ISSUE THREAD

**Issue by PaperOrb** [C-Nedelcu/talk-to-chatgpt#183]
The text-to-speech can do multiple languages, but what about speech-to-text? I've tried speaking spanish, but it only seems to be listening for English speech input in my case (I didn't select any specific languages for speech input either). Is this possible?

**Comment by C-Nedelcu** [comment]
hello,
there is no other way I'm afraid: you need to select the speech to text input in the settings. 
the speech recognition is performed by a browser API, and they don't support multi-language, they will only do 1 single language that you have to select beforehand.
