### ISSUE TITLE
How to change to custom multi-language voices?

### ISSUE THREAD

**Issue by ForxBase** [C-Nedelcu/talk-to-chatgpt#184]
I would like to change the voice from "English only" to my custom voices in multi-language. Right now I can only see the option to use the default "auto-detect" voices in multi-language. My custom voices are only listed in "English only".

Best regards.

**Comment by resultsinadvance** [comment]
i have installed 2.7.2 for edge and microsoft david and zira are working. not other voices are working. also my elevenlabs is connected but is no longer working. i double checked my api key.

**Comment by C-Nedelcu** [comment]
> i have installed 2.7.2 for edge and microsoft david and zira are working. not other voices are working. also my elevenlabs is connected but is no longer working. i double checked my api key.

you need to open a new issue for this and I will ask you a bunch of questions such as checking for conflicts and whatnot.
I have checked now just in case and v2.7.2 is working fine on my side, there is no breaking change from openAI that can explain this, so there has to be a simple solution on your side that I can help you identify. Please post a new Issue :)

**Comment by resultsinadvance** [comment]
it's working now!

let me know if you want to set up a time to see what I'm building with it
on www.relaxwithadam.com/hugs
