### ISSUE TITLE
Autosend triggers the image file selector

### ISSUE THREAD

**Issue by rolling-one** [C-Nedelcu/talk-to-chatgpt#189]
![2023-10-08 11 03 19](https://github.com/C-Nedelcu/talk-to-chatgpt/assets/18146934/fcf9708a-830f-4f2e-991e-457003b8c440)

**Comment by C-Nedelcu** [comment]
thank you - I have confirmed the problem, should be an easy fix.

I have temporarily unpublished the extension from the store pending resolution of this problem (if I don't I'll get 1-star review bombed as always)

**Comment by C-Nedelcu** [comment]
This is fixed in v2.8.1 

I'm uploading the new version to the Chrome store, it should be approved within 2-3 days.

**Comment by artgecko75** [comment]
Hi! I have the exaxt same issue, but it opens my File explorer - will it be fixed with your patch?

**Comment by C-Nedelcu** [comment]
> Hi! I have the exaxt same issue, but it opens my File explorer - will it be fixed with your patch?

hello,
Yes, that is correct, it will be fixed by this patch.
You can try installing the latest version manually right now if you want (instructions given on the project home page).
But I expect the new version to be available as soon as tomorrow on the Chrome store.

**Comment by C-Nedelcu** [comment]
V2.8.1 is now live on the Chrome store.

Can someone confirm that the bug doesn't occur anymore when using the latest version?
Thanks!

**Comment by rolling-one** [comment]
> V2.8.1 is now live on the Chrome store.
> 
> Can someone confirm that the bug doesn't occur anymore when using the latest version? Thanks!

Hi! The bug is fixed in 2.8.1. However, it doesn't seem to hear me. The bar turns red, I talk, nothing happens, and the bar turns grey. (Maybe it's due to my VPN, maybe it's not.)

**Comment by C-Nedelcu** [comment]
> > V2.8.1 is now live on the Chrome store.
> > Can someone confirm that the bug doesn't occur anymore when using the latest version? Thanks!
> 
> Hi! The bug is fixed in 2.8.1. However, it doesn't seem to hear me. The bar turns red, I talk, nothing happens, and the bar turns grey. (Maybe it's due to my VPN, maybe it's not.)

there hasn't been any changes on that front. Still works properly for me.
Does this work for you? https://www.google.com/intl/en/chrome/demos/speech.html
