### ISSUE TITLE
Activation phrase.

### ISSUE THREAD

**Issue by ElCougnou** [C-Nedelcu/talk-to-chatgpt#19]
It's really amazing, thank you so much! I would just like to be able to activate it with a keyword like Alexa and it would be perfect.

**Comment by dev-eduka** [comment]
Would this imply that the microphone is constantly listening, but not sending anything to ChatGPT,

And then suddenly you say some words that will begin active voice recognition and then the messages will be sent?

In any case, for an activation phrase, the microphone must somehow be listening. So ... that's kinda bad right?

I could consider it for v1.7

**Comment by JeffHox** [comment]
Yes I love this extension also and would love to see activation and deactivation phrase implemented.    It would be awesome to simply leave the tab open all the time and activate and deactivate communication with chat gpt with your voice. making using it throughout your day when you have random thoughts or questions super simple.  And ya that would mean leaving the microphone open but lots of people already do that for Alexa or google assistant.     

thanks for taking people inputs on your awesome extension :)

**Comment by C-Nedelcu** [comment]
I haven't implemented this in v2.0 sorry, but I am thinking about it for a future update. It's a good idea

**Comment by C-Nedelcu** [comment]
This has been implemented in v2.2.0 which I just published.
I hope you like it!
