### ISSUE TITLE
TTS Voice is not speaking (Extension version 2.8.1, Chrome Version 118.0.5993.70, GPT-3.5, GPT-4 default)

### ISSUE THREAD

**Issue by bartman081523** [C-Nedelcu/talk-to-chatgpt#196]
TTS Voice is not speaking 
Extension version 2.8.1, commit aa1d90c06521171b46b7eccb55060de2335bdf9c
Error is in GPT-3.5, GPT-4 (default mode)
Chrome Version 118.0.5993.70)

The extension recognizes my words and writes and sends my question to ChatGPT, 
but when ChatGPT answers, the answer is not spoken out (TTS fails)

- I have reset Chromes Data **(there is no button to reset the default settings for the extension)**
- I have restarted Chrome
**: result is the same**

**I downgraded to 2.8.0, which fixes the error :**

```
git clone https://github.com/C-Nedelcu/talk-to-chatgpt
cd talk-to-chatgpt
git checkout 0657f0f6b74c7948ce74b6126fbdfae2d3febcac
```

then I add the talk-to-chatgpt/chrome-extension directory in Chrome as "unpacked Extension"

**Comment by C-Nedelcu** [comment]
hello,

could you please provide the javascript console log and more data from the chrome inspector when you encounter such issues?

I use the plugin regularly with ElevenLabs, and I do not encounter this error.

However, sometimes Chrome decides to stop all audio from working in the plugin (including the beep noises). I have to fully close Chrome and reopen it for it to work. I have yet to figure out a way to systematically reproduce this problem and fix it.

**Comment by bartman081523** [comment]
I fixed the bug by downgrading Google Chrome to 114.0.5735.198-1, up from Chrome v115 the STT is not written in the text field
