### ISSUE TITLE
Polly Voices

### ISSUE THREAD

**Issue by Chip819** [C-Nedelcu/talk-to-chatgpt#20]
Hello,

I use the voices from Amazon Polly AWS because the quality is very good but I can't use them with talk-to-chatgpt extension because only Google or Microsoft voices are listed.

Do you think that it is possible for you to add the Amazon Polly in the parameter voices list in a near futur?

Thank you. 

![VOICES](https://user-images.githubusercontent.com/122698349/212494698-cd9f9a72-8c8a-482f-a42b-12ad25ef9024.jpg)

**Comment by OliverRovesik** [comment]
Agree. It'd be fantastic to have this voice.

**Comment by dev-eduka** [comment]
hi,
does the voice appear on this demo: https://www.google.com/intl/en/chrome/demos/speech.html ?

**Comment by OliverRovesik** [comment]
Nope. There are only two options. One for language and the other for Country/region,

**Comment by C-Nedelcu** [comment]
Then Google Chrome will not be able to use that voice through its standard API.
This is something you need to request either to Google or to Amazon (whichever will agree to do the job).
Unfortunately I cannot assist in implementing this. As much as I would like to be able to use that voice - it's pretty great indeed
