### ISSUE TITLE
Request for OpenAI API support

### ISSUE THREAD

**Issue by Ailerath** [C-Nedelcu/talk-to-chatgpt#207]
Requesting that OpenAI toggle like ElevenLabs for OpenAI API TTS

Also, request that a Whisper STT toggle be added as the key will be given for TTS anyway.

**Comment by C-Nedelcu** [comment]
If you want alternatives for TTS you can try Azure TTS which is free and was implemented in v2.9.0

Whisper is much more complicated to implement - I have ran into trouble trying to do it.
