### ISSUE TITLE
'Respond' word

### ISSUE THREAD

**Issue by GitHubmembrane** [C-Nedelcu/talk-to-chatgpt#21]
Hello, great extension.

Just like you have a 'Stop' word and a 'Pause' word, could you add also an optional 'Respond' word.
The benefit would be that if you want to say something to ChatGPT the way it is now, you always feel the pressure to say the whole thing without pausing and that is uncomfortable and at times not possible because sometimes you have to pause and think of what you want to say in mid sentence but currently you cannot do this because the extension will send the incomplete sentence that you started saying to chatgpt.

But if there is a 'Respond' word then you can pause as long as you want and as often as you want and then when you are done with what you wanted to say then you say your 'Respond' word and then you get chatgpt to respond to you. Just like when people are talking over Walkie Talkies they use the word "Over" which means I’m done with my transmission, ready for your reply

**Comment by OliverRovesik** [comment]
Agree, this would be fantastic.

**Comment by dev-eduka** [comment]
Great idea. Will be added in v1.6 :)

**Comment by dev-eduka** [comment]
V1.6 is now available - download from github and sideload
OR wait until v1.6 is approved by Google and posted on the app store

The update includes this feature request. Hope you like it!

**Comment by GitHubmembrane** [comment]
It works great thank you. The way you did it also gives you the opportunity to edit the text if there were any mistakes from the transcription before sending it to chatgpt
