### ISSUE TITLE
Will respond to 1 initial prompt, then ceases to work.

### ISSUE THREAD

**Issue by Ubuntufoo** [C-Nedelcu/talk-to-chatgpt#22]
I've tried logging out/in , reinstalling extension, checking mic settings. It is only allowing an initial prompt at best. Usually I test it with a "hello" to gauge server stability and that is working ok, then following that there is no more STT function. Standard keyboard prompts continue to work fine. 

Sometimes I see a red ribbon, followed by a green ribbon, attached to the bottom of the extension widget but it goes away. Sometimes I hear an "ok" from the extension, and I have brief functionality. What are these ribbons telling me?

**Comment by Ubuntufoo** [comment]
Update: I got through 6 prompts, then turned off the bot voice. This is when all extension functionality ended. Once I reset everything and regained functionality I tried again and got through several prompts successfully; I then pressed "skip this message played by bot" and my functionality ended. Do with that what you will. GL.

**Comment by dev-eduka** [comment]
I have tried addressing this issue in v1.6 which is now available
The update is under review before appearing on the app store.
But if you want to try it manually right now you can get the zip file and sideload it.
