### ISSUE TITLE
no ai voice can be selected in Brave using extension

### ISSUE THREAD

**Issue by akdaddy** [C-Nedelcu/talk-to-chatgpt#23]
If you install this in Brave browser it doesnt work because there is no selectable ai voice as it is in chrome so is there an easy fix to this. thanks

**Comment by C-Nedelcu** [comment]
I am really sorry but this extension will only work in Google Chrome due to API supports. I am not going to be technically able to make the same extension for any other browsers or forks thereof (see FAQ).
