### ISSUE TITLE
Speech input does not work on Android (Kiwi browser)

### ISSUE THREAD

**Issue by snorrehu** [C-Nedelcu/talk-to-chatgpt#26]
I tried adding this extention to the Kiwi browser on my Huawei Mediapad T5. It reads the responses just fine, but it doesn't open up for speech input.

**Comment by snorrehu** [comment]
I suspect that this is a permission issue on my device, but it does not work even tough I've granted micriphone permission for the browser and the site.

**Comment by C-Nedelcu** [comment]
Hello,
As stated in the readme/FAQs/extension popup - this extension will only work with Google Chrome Desktop version. This is due to current support for TTS/STT APIs. 
I am afraid I have to close this now.

**Comment by snorrehu** [comment]
Ah sorry I didn't catch that. Anyway - the extention is awesome!
