### ISSUE TITLE
Ukrainian speech synthesis

### ISSUE THREAD

**Issue by Nevernighty** [C-Nedelcu/talk-to-chatgpt#27]
I have found only instructions on how to add speech recognition in the extension code, but couldn't find where it pulls the speech synthesis besides voice.lang stuff. Can you add Ukrainian as a TTS? ChatGPT can talk it, and google has the TTS for Ukrainian existing...

**Comment by C-Nedelcu** [comment]
Hello
do you see Ukrainian in this demo? https://zolomohan.com/text-to-speech/
This is a demo of the standard Google Chrome API text to speech functionality. That's where the voices come from. 
If Ukrainian isn't in the dropdown list, then I simply cannot make it happen.

**Comment by Nevernighty** [comment]
What about other ways? I've seen Ukrainian in other extensions that use same voices, is it possible to change API It pulls voices from?

I've found these
https://www.google.com/intl/en/chrome/demos/speech.html
https://speechify.com/blog/best-text-to-speech-chrome-extension/

and others that do support Ukrainian with google tts

**Comment by winson7325** [comment]
https://www.youtube.com/watch?v=GOFvOdWdnNM&lc=Ugz7PLL9_wPSteqleU14AaABAg.9n7n_6mtxeX9nBtGQEvfvd

27:12 How did he do it then
