### ISSUE TITLE
Option for Amazon Polly

### ISSUE THREAD

**Issue by Ty-lerCox** [C-Nedelcu/talk-to-chatgpt#28]
I have pulled down the project and attempted to add this myself, but Amazon's Polly API generates very pleasant speech-to-text.

I wish there were an option or adding an AWS API key and selecting an Amazon Polly's voice.

**Comment by Ty-lerCox** [comment]
`function CN_SayOutLoud(text) {
	console.log(text);
	if (!text || CN_SPEAKING_DISABLED) {
		if (CN_SPEECH_REC_SUPPORTED && CN_SPEECHREC && !CN_IS_LISTENING && !CN_PAUSED && !CN_SPEECHREC_DISABLED) CN_SPEECHREC.start();
		clearTimeout(CN_TIMEOUT_KEEP_SPEECHREC_WORKING);
		CN_TIMEOUT_KEEP_SPEECHREC_WORKING = setTimeout(CN_KeepSpeechRecWorking, 100);
		return;
	}
	
	// Are we speaking?
	if (CN_SPEECHREC) {
		clearTimeout(CN_TIMEOUT_KEEP_SPEECHREC_WORKING);
		CN_SPEECHREC.stop();
	}
	
	// Let's speak out loud
	console.log("Saying out loud: " + text);
	
	AWS.config.update({
		accessKeyId: "",
		secretAccessKey: "",
		region: "us-east-1"
	});
	
	var polly = new AWS.Polly();
	
	var params = {
		OutputFormat: "mp3",
		Text: text,
		VoiceId: "Joanna"
	};
	
	polly.synthesizeSpeech(params, function(err, data) {
	if (err) {
		console.log(err, err.stack);
	} else {
		var uInt8Array = new Uint8Array(data.AudioStream);
		var arrayBuffer = uInt8Array.buffer;
		var blob = new Blob([arrayBuffer]);
		var audioElement = new Audio();
		audioElement.src = URL.createObjectURL(blob);
		audioElement.play();
	}
	});
}`

This almost works. The tracks are overlapping on one another.

**Comment by Ty-lerCox** [comment]
Again, clunky implementation, but this almost works:

```
var tracks = [];
var isSpeaking = false;

function CN_SayOutLoud(text) {
	console.log(text);
	if (!text || CN_SPEAKING_DISABLED) {
		if (CN_SPEECH_REC_SUPPORTED && CN_SPEECHREC && !CN_IS_LISTENING && !CN_PAUSED && !CN_SPEECHREC_DISABLED) CN_SPEECHREC.start();
		clearTimeout(CN_TIMEOUT_KEEP_SPEECHREC_WORKING);
		CN_TIMEOUT_KEEP_SPEECHREC_WORKING = setTimeout(CN_KeepSpeechRecWorking, 100);
		return;
	}
	
	// Are we speaking?
	if (CN_SPEECHREC) {
		clearTimeout(CN_TIMEOUT_KEEP_SPEECHREC_WORKING);
		CN_SPEECHREC.stop();
	}
	
	// Let's speak out loud
	console.log("Saying out loud: " + text);
	
	AWS.config.update({
		accessKeyId: "",
		secretAccessKey: "",
		region: "us-east-1"
	});
	
	var polly = new AWS.Polly();
	
	var params = {
		OutputFormat: "mp3",
		Text: text,
		VoiceId: "Joanna"
	};
	
	polly.synthesizeSpeech(params, function(err, data) {
		if (err) {
			console.log(err, err.stack);
		} else {
			var uInt8Array = new Uint8Array(data.AudioStream);
			var arrayBuffer = uInt8Array.buffer;
			var blob = new Blob([arrayBuffer]);
			tracks.push(blob);
			CN_SpeakAllTracks();
		}
	});
}

function CN_SpeakAllTracks() {
	if (tracks.length == 0) {
		CN_AfterSpeakOutLoudFinished();
		return;
	}
	
	if (isSpeaking) {
		return;
	}
	isSpeaking = true;
	var track = tracks.shift();
	var audioElement = new Audio();
	audioElement.src = URL.createObjectURL(track);
	audioElement.play();
	audioElement.onended = function() {
		isSpeaking = false;
		CN_SpeakAllTracks();
	};
}

**Comment by Ty-lerCox** [comment]
https://github.com/Ty-lerCox/talk-to-chatgpt

Here is a hacky implementation of it.

**Comment by C-Nedelcu** [comment]
Would you kindly record a quick video or something so we can understand how much of an improvement it is over the default voices?

**Comment by C-Nedelcu** [comment]
Hello there,

I have added ElevenLabs API support in v2.6.0.
It's been requested by a lot of people, and I believe it's as good as (if not better than) Amazon Polly. 

Considering this, do you still feel that Amazon Polly integration is useful?
If not, I will close the issue.

**Comment by C-Nedelcu** [comment]
closed due to inactivity.
Feel free to reopen later if necessary
