### ISSUE TITLE
Microphone access on phone

### ISSUE THREAD

**Issue by JeffHox** [C-Nedelcu/talk-to-chatgpt#30]
I don't know if its possible but if your extension could request access to your phones microphone when using a chromium based browser like Kiwi that supports extensions then it would work on android phones as well.    I have not been able to find a way to turn on microphone access to the site or your extension without a request being sent from the site or extension.  If someone knows a way that would also be helpful. 

thanks again... awesome extension.

**Comment by JeffHox** [comment]
Ok I found a way to give the website access to the microphone but it still doesn't work with the app..  :(

**Comment by Ashkanfareghi** [comment]
You can give kiwi the mic access, but it still ins't supported yet to speak in kiwi I guess.

**Comment by C-Nedelcu** [comment]
Mobile browsers do not implement the required APIs for this extension to work yet. It's not anything I can do, you just have to wait for the browsers to be updated.
