### ISSUE TITLE
Voix supplémentaires

### ISSUE THREAD

**Issue by FreemanLiberty** [C-Nedelcu/talk-to-chatgpt#31]
Bonjour et un très grand bravo pour votre travail.
Est il possible d'avoir un moyen d obtenir d'autres styles de voix en Français, plus naturelle ?
D'avance merci.

**Comment by C-Nedelcu** [comment]
Vous pouvez installer des voix système dans Microsoft Windows. Ces voix systèmes seront proposées dans le menu une fois installée. Je n'en connais pas personnellement.
