### ISSUE TITLE
Add Ukrainian translation

### ISSUE THREAD

**Issue by cryptogateway** [C-Nedelcu/talk-to-chatgpt#32]
Can you add Ukrainian translation in this application?

**Comment by AIM-1993** [comment]
No, he can't

**Comment by 2oldfords** [comment]
is there a reason other languages be added? is it a limitation of google's languages for speech recognition that you pulled from https://www.google.com/intl/en/chrome/demos/speech.html

**Comment by winson7325** [comment]
підтримую. Дуже хочу добати українську мову!

**Comment by AIM-1993** [comment]
> підтримую. Дуже хочу добати українську мову!

Yeah, because Ukrain belongs to Russia

**Comment by C-Nedelcu** [comment]
I cannot add any languages. Please read the FAQ thank you everyone

**Comment by winson7325** [comment]
> n

https://www.youtube.com/watch?v=GOFvOdWdnNM&lc=Ugz7PLL9_wPSteqleU14AaABAg.9n7n_6mtxeX9nBtGQEvfvd

27:12

**Comment by winson7325** [comment]
https://www.youtube.com/watch?v=GOFvOdWdnNM&lc=Ugz7PLL9_wPSteqleU14AaABAg.9n7n_6mtxeX9nBtGQEvfvd

27:12 How did he do it then

**Comment by AIM-1993** [comment]
If you guys are not Ukrainian, then I think I don't need to talk about it anymore, you choose your own way. But If you are not, read this may help you understand something which you can't see in your country.


NO ONE REALLY NEED WAR, don't be idot


https://user.guancha.cn/wap/content?id=703815&amp;s=fwzwyzzwzbt


Tempo&nbsp;JoKer
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "C-Nedelcu/talk-to-chatgpt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 晚上6:31
***@***.***&gt;;
抄送:&nbsp;"Tempo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [C-Nedelcu/talk-to-chatgpt] Add Ukrainian translation (Issue #32)





 
https://www.youtube.com/watch?v=GOFvOdWdnNM&amp;lc=Ugz7PLL9_wPSteqleU14AaABAg.9n7n_6mtxeX9nBtGQEvfvd
 
27:12 How did he do it then

**Comment by winson7325** [comment]
I am Ukrainian. And I want to communicate in Ukrainian. There is no need for war. Leave our territories, do not bomb our people and our country. I don't understand your message? Are you against Ukraine and the Ukrainian language?

**Comment by C-Nedelcu** [comment]
> https://www.youtube.com/watch?v=GOFvOdWdnNM

you can add voices to your system in microsoft windows. Try to find that on the web. 

My extension doesn't add any voices, it does something very simple, which is to use the voices already installed on your system (microsoft voices) or in your web browser (google voices). In either case, I cannot add them myself. My code is a simple piece of javascript. Feel free to look at the source code :)

**Comment by AIM-1993** [comment]
Sorry, of course not, but it's really evil from the jewish shadow goverment. Maybe your country should not stand with Nato.

Tempo&nbsp;JoKer
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "C-Nedelcu/talk-to-chatgpt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 晚上6:51
***@***.***&gt;;
抄送:&nbsp;"Tempo ***@***.******@***.***&gt;;
主题:&nbsp;Re: [C-Nedelcu/talk-to-chatgpt] Add Ukrainian translation (Issue #32)





 
I am Ukrainian. And I want to communicate in Ukrainian. There is no need for war. Leave our territories, do not bomb our people and our country. I don't understand your message? Are you against Ukraine and the Ukrainian language?

**Comment by winson7325** [comment]
[AIM-1993](https://github.com/AIM-1993) What country are you from? Why do I care what is done in your country? Maybe we ourselves should decide our direction? Don't you think so?

**Comment by winson7325** [comment]
[C-Nedelcu](https://github.com/C-Nedelcu) I understand all this. And didn't mean for you to add to your code. thank you
