### ISSUE TITLE
Unable to hear the voice from ChatGPT and other issues

### ISSUE THREAD

**Issue by 230219LIU** [C-Nedelcu/talk-to-chatgpt#33]
At first, I was free to use the tool and explore all kinds of voices in the setting, but once I tried "Stop" with my voice, it stopped and it was no longer able to generate a voice for ChatGPT(it was not muted). My input function is still working but I have to press ⏩ to input my voice every time. I tried uninstalling and reinstalling the tool but the issue stays the same. PLEASE HELP!! This is an awesome tool for me and other language learners and I want to keep using it! Thanks

**Comment by C-Nedelcu** [comment]
hello,
could you confirm if you still have this issue as of the latest version v2.2.0 which I published just now?
thanks

**Comment by C-Nedelcu** [comment]
If the issue persists try the new ElevenLabs option from v2.6.0
