### ISSUE TITLE
Add ElevenVoice API Integration

### ISSUE THREAD

**Issue by MatthewSabia1** [C-Nedelcu/talk-to-chatgpt#34]
This would be the ultimate new feature in my opinion. The ability to interact with the AI as a cloned voice of any person in a realistic fashion.

Their API docs can be found here: https://api.elevenlabs.io/docs

**Comment by boluda** [comment]
That would be fantastic. ElevenLabs Speech Synthesis is fricking awesome.

https://beta.elevenlabs.io/speech-synthesis

Would that integration be possible?

**Comment by boluda** [comment]
Maybe this can help? -> https://github.com/1nnovat1on/gpt_chatbot

This chatbot lets you use your microphone to communicate with GPT-3. It uses the ElevenLabs API to respond with a realistic voice.

**Comment by MatthewSabia1** [comment]
> Maybe this can help? -> https://github.com/1nnovat1on/gpt_chatbot
> 
> This chatbot lets you use your microphone to communicate with GPT-3. It uses the ElevenLabs API to respond with a realistic voice.

That's great, BUT, that is if you don't mind paying for the regular OpenAI services and it's not as simple as just using ChatGPT.

**Comment by boluda** [comment]
> > Maybe this can help? -> https://github.com/1nnovat1on/gpt_chatbot
> > This chatbot lets you use your microphone to communicate with GPT-3. It uses the ElevenLabs API to respond with a realistic voice.
> 
> That's great, BUT, that is if you don't mind paying for the regular OpenAI services and it's not as simple as just using ChatGPT.

Ohhhh, what a bummer. Sorry Matthew, I thought it was for ChatGPT. Do you think you could integrate ElevenLabs Speech Synthesis on ChatGPT in your Chrome extension? That would be epic. Let me know if I can help somehow.

And thanks for the extension, works like a charm.

**Comment by shun4423** [comment]
Hello! ElevenLab is indeed a free plan, with a limited number of characters available, so it may not be for you. However, non-native speakers like myself may want to pay for it and still speak in a more natural machine voice.

**Comment by boluda** [comment]
I'm already paying for ElevenLabs service (I have some custom voices), I would love to hear ChatGPT speaking with those great voices.

**Comment by joeworrall** [comment]
Please can you tell us how to add languages to the google API? For example, speechSynthesis.getVoices() returms a basic list of only *some* of the supported languages in the google TTS API. What am I missing? There are many, many languages available in the google API that do not show up. Thank you!

**Comment by C-Nedelcu** [comment]
Hello there,

I have added ElevenLabs API support in v2.6.0.

This version has not been submitted to the Chrome/edge stores yet, I think it would need some beta testing first.
Would anyone please give it a try?

You have to install the new version manually, instructions are given on the project's home page.

I hope you enjoy it. I had fun testing it, the ElevenLabs voices are pretty great - even the default ones with a Free account.

**Comment by drorm** [comment]
Did a quick trial as well. Works nicely.
The API key is hidden in the user profile page on https://beta.elevenlabs.io/speech-synthesis for anyone else who wants to try.
It's fascinating to experiment with the bilingual voices. Too bad they're way more expensive than AWS or GC.

**Comment by C-Nedelcu** [comment]
this has been live for a few days and seems to be working pretty great, so I'm going to close the issue :)

**Comment by boluda** [comment]
OMG, this integration works really awesome! So you finally did it? Awesome! This is sooo cool! Kudos to you! So, is this still a side project?

**Comment by C-Nedelcu** [comment]
Thanks for your kind words. 
Yes, I work on it a few hours every week-end for fun. I'm glad this is helping people 👍 
I've got awesome ideas for new features though, can't wait to implement them!

**Comment by drorm** [comment]
Did a quick trial as well. Works nicely.
The API key is hidden in the user profile page on https://beta.elevenlabs.io/speech-synthesis for anyone else who wants to try.
It's fascinating to experiment with the bilingual voices. Too bad they're way more expensive than AWS or GC.

**Comment by boluda** [comment]
Well, the 11labs integration works awesome, kudos to you. If we can help somehow, let us know!

**Comment by drorm** [comment]
@C-Nedelcu I've got a bit of bandwidth, so I can help a bit. 
I archived https://github.com/drorm/leah since I couldn't quite do with it what I wanted with the restrictions of being in the opeanai environment.
Feel free to ping me on a ticket, and I'll confirm that it's something that works for me, we'll go from there.
Obviously, I'm familiar with the whole Chrome extension, voice recognition and TTS.

**Comment by C-Nedelcu** [comment]
> Well, the 11labs integration works awesome, kudos to you. If we can help somehow, let us know!

What keeps me going is basically positive and/or constructive feedback, so a nice review on the Chrome store is always appreciated. It kind of brings me down when someone posts a 1-star review like _"that doesnt work at all!! this extension is shit!!"_ That's the opposite of helpful, if only they would tell me what's wrong so I could help them out. But I guess that's how things are nowadays, everything's expected to work smoothly - even experimental/fun free software. Anyhow, I also enjoy a bit of publicity here and there, like social media shares or blog posts and whatnot, this always helps increase the user base and helps motivation.

The main thing I'm working on at the moment is an "interpreter mode". It will allow you to have an actual conversation with someone in a foreign language, with immediate & accurate back and forth translation. I'm also looking at other suggestions from users, lots of good ideas have been dropped, this is quite fun to work on overall!

**Comment by boluda** [comment]
Oh, sure! I'm constantly recommending your Chrome Extension [on my podcast](https://itunes.apple.com/es/podcast/podcast-marketing-online/id879629380) (70.000 daily listeners). I'll do it again this week to talk about 11labs integration.

The interpreter mode sound awesome, very helpful indeed!
