### ISSUE TITLE
How come Edge cannot be supported? There are MS speech for asia languages in Edge

### ISSUE THREAD

**Issue by yahgoo** [C-Nedelcu/talk-to-chatgpt#35]
I installed this extension. It works only once. Subsequently, it cant work. There is no red/green ribbon.

How come Edge cannot be supported? There are MS speech for asia languages in Edge

**Comment by OliverRovesik** [comment]
For me (MacOs), the text-to-speech functionality works while speech-to-text doesn't. So I use the system built-in speech-to-text instead.

**Comment by C-Nedelcu** [comment]
as you can see here:
https://caniuse.com/speech-recognition
HTML5 speech-to-text API isn't supported under Edge

**Comment by yahgoo** [comment]
Thanks for explaining the limitation of Edge. Your chrome extension works on Chrome. Is it possible to have MS voice as AI voice and language because I need the English (Singapore) TTS?

**Comment by yahgoo** [comment]
Good news. I installed Edge Beta Version 111.0.1660.13 (Official build) dev (64-bit). Your App works.

**Comment by jt-github** [comment]
Working on Edge for me on two different Windows 11 PCs.

**Comment by C-Nedelcu** [comment]
Microsoft fixed it! closing this now

**Comment by johnmatthewtennant** [comment]
Is this fixed on mac too?
