### ISSUE TITLE
Problem with Brave .

### ISSUE THREAD

**Issue by BTCWFD** [C-Nedelcu/talk-to-chatgpt#36]
The extension does not work well in the Web Browser Brave has problems with the microphone.

**Comment by lucgerrits** [comment]
Same. It doesn't find the mic or something.

**Comment by lyctw** [comment]
Same problem

**Comment by C-Nedelcu** [comment]
I am very sorry but as the FAQ & extension popup clearly state only Google Chrome (desktop) is supported. No other browsers will be actively supported. That being said, if someone is willing to make a pull request I won't reject it, provided it doesn't break compatibility with Google Chrome (desktop).

**Comment by pinturic** [comment]
I am having the same problem and it seems that simple Brave does not implement speech recognition APIs:
1. https://stackoverflow.com/questions/74113965/speechrecognition-emitting-network-error-event-in-brave-browser
2. https://github.com/brave/brave-browser/issues/2802

So there is nothing that can be done unless a polyfill is used: https://www.speechly.com/blog/full-browser-compability-webspeech-api/
