### ISSUE TITLE
Pop-up

### ISSUE THREAD

**Issue by Nokuzen** [C-Nedelcu/talk-to-chatgpt#37]
Hello, I'm using these extensions, but I have a problem with a pop-up that asks me to confirm the message sending. I tried to disable it in Chrome, but it didn't change anything, it still asks me to confirm before sending.

**Comment by C-Nedelcu** [comment]
Could you please provide a screenshot? I am not sure what popup you are talking about. It might not be related to my addon, but I'd like to be sure
