### ISSUE TITLE
speech recognition stops after a short pause

### ISSUE THREAD

**Issue by jeffweisbein** [C-Nedelcu/talk-to-chatgpt#39]
Would it be possible to have a setting to increase the time you have between pauses in speaking to ChatGPT? I've used the extension to create a bot for a social audio app and when people talk to the bot account if they stop speaking for a moment, it assumes they're done and starts to process what has already been said (but they aren't finished with what they're actually saying, they just paused to think).

Any insights on this? Thanks!

**Comment by C-Nedelcu** [comment]
Hello Jeff,
This could be an idea for a future update.
Have you considered using the manual send option from v1.6.2 ? 
Basically, you disable autosend, and you select a send word.
I am not sure whether your comment was made before or after I published that feature.

**Comment by lucasdourado8** [comment]
I came here to suggest the same thing. Regarding the manual sending function, I think you could leave the prompt without the text appearing (as in the automatic function). This appearing text shapes the way I communicate and disrupts the flow of language. It would seem a lot like an automatic function but I can give it all the time to think and give more context to the sentence and only then say the word send. It would be amazing for someone who is studying other languages.

**Comment by C-Nedelcu** [comment]
This has been implemented in v2.2.0 which I just published.
I hope you like it!
