### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by 6DiegoDiego9** [C-Nedelcu/talk-to-chatgpt#4]
At first try it didn't work on Chrome/Edge on Android.
Is it supposed to work on Android?

**Comment by C-Nedelcu** [comment]
Hello,
No, it is only supposed to work on Google Chrome Desktop due to API availability. This is in the FAQ on the main readme if you want more information.

**Comment by 6DiegoDiego9** [comment]
Thanks for the answer.
In the meantime I managed to use it on my Android phone via Remote Desktop (to my PC)
