### ISSUE TITLE
chatgpt 的网页并不好用，希望可以使用自己的api

### ISSUE THREAD

**Issue by xiaolongbaox** [C-Nedelcu/talk-to-chatgpt#49]
由于使用的人太多，gpt的网页并不好用，仅对话两三次就需要刷新页面才能继续对话。希望可以实现在本地通过api和和chatgpt语音对话，这可以是一个脚本，app，或者其他。
/感谢你开发的浏览器扩展

**Comment by hahahumble** [comment]
可以试试这个 https://github.com/hahahumble/speechgpt

**Comment by C-Nedelcu** [comment]
> 可以试试这个 https://github.com/hahahumble/speechgpt

Very nice project. It's a bit different than mine, because yours uses the API, whereas mine relies on the current ChatGPT HTML DOM/UI. You can definitely do a lot more with a project like yours. Mine is very limited. Good luck!

**Comment by xiaolongbaox** [comment]
> 可以试试这个 https://github.com/hahahumble/speechgpt

https://github.com/C-Nedelcu/talk-to-chatgpt/issues/49#issuecomment-1487866954

**Comment by xiaolongbaox** [comment]
> 可以试试这个 https://github.com/hahahumble/speechgpt


好东西，和我想要的完全一样，谢谢你的开发
