### ISSUE TITLE
No Permission Pop-Up in Brave Browser

### ISSUE THREAD

**Issue by chrubble** [C-Nedelcu/talk-to-chatgpt#52]
I have installed the extension in Brave and set extension permissions to allow microphone use. When I am in ChatGPT and click 'START' for Talk-to-ChatGPT, the extension says 'OK', but there is no pop-up for microphone permission. Speech is not registered. Brave settings are set to allow 'Sites can ask to use your microphone', and Talk-to-ChatGPT is listed in allowed extensions.

**Comment by chetryJyoti** [comment]
I think because it is not compatible with brave browser

**Comment by C-Nedelcu** [comment]
This extension will only work with Google Chrome Desktop as stated in the FAQ.
