### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by abrichr** [C-Nedelcu/talk-to-chatgpt#54]
Thank you for the wonderful contribution!

I want to talk to ChatGPT while on a walk. Is this use case supported? If not, what are the steps involved in implementing it?

Thanks again! 🙏 

Edit: for reference there is the [SiriGPT Siri shortcut](https://www.reddit.com/r/shortcuts/comments/11gcpof/sirigpt_update_access_the_chatgpt_api_through_siri/), but it appears to be closed source, and requires configuring an OpenAI API key, and prefixing everything with "Hey Siri, SiriGPT..." -- it is also responding with an empty string for me on iOS 16.3.1.

**Comment by C-Nedelcu** [comment]
Hello,
Sorry, this extension will only work with Chrome Desktop version.
The mobile browsers do not currently support the required APIs for web speech.
