### ISSUE TITLE
talk to chatgpt error, she is starting with this word "1 over 1" and then read the answer.

### ISSUE THREAD

**Issue by chanohinu** [C-Nedelcu/talk-to-chatgpt#55]
like i said on title, when i ask something, CHAT GPT is starting with this word "1 over 1" and then read the answer.
how can i fix this? i deleted talk to chatgpt on chrome and restart my computer but it`s not working and this error repeated.

**Comment by enrix5077** [comment]
It is not responding automatically either, how sad I feel.

**Comment by C-Nedelcu** [comment]
This has been addressed in v1.6.2. Closing the issue
