### ISSUE TITLE
error in talk to chatgpt it is not responding automatically

### ISSUE THREAD

**Issue by enrix5077** [C-Nedelcu/talk-to-chatgpt#56]
please help talk to chatgpt is not working correctly, it is reading some numbers at the beginning of the response, and it is not responding automatically either, a few hours ago it began to give this problem, I already restarted the pc, I even have 2 plus accounts in none It also works, I changed to a different PC and it doesn't work either, what happens? please help.

**Comment by C-Nedelcu** [comment]
Hello,
v1.6.2 fixed this issue. Thanks for using my extension
