### ISSUE TITLE
the prompt is not sent automatically

### ISSUE THREAD

**Issue by jean-pasqualini** [C-Nedelcu/talk-to-chatgpt#57]
The checkbox to send the message automatically is checked though the extension doesn't manage to send the message, probaly the extension need an upgrade

**Comment by C-Nedelcu** [comment]
Thanks - the ChatGPT UI has been updated and the extension no longer works properly.

It needs an update as you said.

**Comment by bartman081523** [comment]
1.6.2 update fixes this.

**Comment by C-Nedelcu** [comment]
Thanks, indeed v1.6.2 fixed the issue. I am closing this
