### ISSUE TITLE
Not talking in Chinese

### ISSUE THREAD

**Issue by rjda11** [C-Nedelcu/talk-to-chatgpt#59]
I am having no luck getting the extension to talk to me in Chinese. The browser I am using is Edge.
Should it work with Edge browser? Am I doing something wrong with the settings? 
Here are my settings:

![TalkToChatgpt Settings](https://user-images.githubusercontent.com/130098502/230666342-c1dc640b-4055-4b71-810e-08fca4e6a896.jpg)

**Comment by C-Nedelcu** [comment]
Hello,
Have you tried using another AI voice? (the first setting)
Try using Google Chrome, and using the chinese voice from Google. 
It works great for me.

Unfortunately, this isn't something I'll be able to fix or control in any way. This is on the system side, there's nothing I can do from web.

**Comment by rjda11** [comment]
The Chrome browser with the Chinese voice from Google works!
Thanks!

NOTE: On the Edge browser none of the Google voices show up - only ones
that start with Microsoft.

**Comment by rjda11** [comment]
Hi, 
The Chrome browser with the Chinese voice from Google works! 
Thanks! 

NOTE: On the Edge browser none of the Google voices show up - only ones 
that start Microsoft. 

Robert
