### ISSUE TITLE
fix , I can change the settings 

### ISSUE THREAD

**Issue by reihun** [C-Nedelcu/talk-to-chatgpt#6]
fix , I can change the settings . It is blocked

**Comment by stefanristic123** [comment]
Go to inspect elements => Elements => finde <span> click on it, now go to styles and add in 
elemnent.styles {
    
    z-index: 1111;
    position: absolute;
}

leave everyting in elemnent.styles just add these two properties

**Comment by C-Nedelcu** [comment]
Thank you for bringing this up, this has been resolved. 
V1.3.1 (thanks @RainDance74 )
