### ISSUE TITLE
Problems with Chrome

### ISSUE THREAD

**Issue by lucasdourado8** [C-Nedelcu/talk-to-chatgpt#61]
As soon as I finish saying something, Chrome displays this message: Are you sure you want to continue? The current prompt text will be lost. and i have to choose between ok and cancel.

**Comment by C-Nedelcu** [comment]
Hello,
I think you must be using another extension that is in conflict with Talk-To-ChatGPT.
Please make sure:
- you are using Chrome latest version, desktop (mobile not supported)
- you are not using any other extensions that might be interfering with Talk-to-ChatGPT
