### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by pixelsoda** [C-Nedelcu/talk-to-chatgpt#62]
Hello, I'd like to offer a a better gui for this fantastic project of yours, free of charge of course. Let me know if you're interested and I'll whip something up for you.

**Comment by C-Nedelcu** [comment]
hello,
Very generous of you, what do you have in mind ? would you have any samples of your past work ?
To be fair I don't really believe this extension warrants a wonderful GUI. It's just a little tool I made for fun. It will sooner or later be disfunctional or obsolete when OpenAI revamp their ChatGPT page.
I'm still open to hearing you out though and see where it leads us.

**Comment by pixelsoda** [comment]
Not a problem at all. Your app has already been of great help to many of us, and I'm happy to return the favor. It's not much but I hope you can make use of it. Thanks again.

![Screenshot 2023-04-12 at 9 33 27 AM](https://user-images.githubusercontent.com/130507286/231474869-0028944a-0a32-4a8c-b30a-440e8271c35a.png)

**Comment by C-Nedelcu** [comment]
That looks really sleek. I'd love to have an UI like this. Are you able to send me an HTML source and/or CSS so I can implement this design?

**Comment by C-Nedelcu** [comment]
I have never used Illustrator and am as much a designer as you are a developer, I'm afraid. I'll ask around to see if there's an easy way to turn this into HTML.

**Comment by pixelsoda** [comment]
We're total opposites =) Well, the .ai file is at work so  I'll send the file to you first thing tomorrow morning. It's not some top secret document so uploading here will be fine.  Sorry I couldn't assist with the conversion process.

**Comment by pixelsoda** [comment]
Looks like the comment section doesn't support the upload of .ai file.

**Comment by pixelsoda** [comment]
![TalkGPT UI](https://user-images.githubusercontent.com/130507286/232150049-a66d487c-d7d1-494e-aec3-4f9d5b3de2d1.png)

**Comment by C-Nedelcu** [comment]
Thank you very much, may I ask what font you are using?
I have sent this to a designer friend and he turned it into HTML/CSS. 
I should be able to integrate it soon.

**Comment by pixelsoda** [comment]
The pleasure is mine. Though I would probably ask your designer to use a font that's available to him. To be honest, I'm not quite satisfied with the way I capitalized "TALK TO" and maybe he could use a font he has and also make some minor tweaks to it. But feel free to let me know if you have any other question!

**Comment by C-Nedelcu** [comment]
I've just pushed v2.1.0 to Github with the new UI.
It's very close to your design but not 1:1 because I couldn't get the right icons (the ones I used are from fontawesome).
Still, it's a great improvement. Thanks for your contribution! I have credited you on the extension popup and in the github commits.

Would you give it a try and see if it's close to what you had in mind?

**Comment by pixelsoda** [comment]
Wow, that's fantastic news! It's great to hear that the UI works. Your app has been an incredible resource for many of us, and I'll be sure to inform you of its appearance once I've successfully reinstalled it. Thank you!
