### ISSUE TITLE
could add the featrue that people could speak "clean word" to clean text in textbox

### ISSUE THREAD

**Issue by xiahan4956** [C-Nedelcu/talk-to-chatgpt#63]
The extenion is very useful!
I open it and use it all day.

Many times ,I find text box have many words I have said. But these words are not aim to chatgpt . Instead, they are just normal conversations I have had with other people.

so if add a feature which could clean text box by say "clean words",it is very useful

I am Chinese,I would say "清空对话".

Thanks!

**Comment by C-Nedelcu** [comment]
亲爱的朋友，我并没有冒犯的意思，但我很难理解你的问题。你能否请用中文再发一遍问题？谢谢你的理解。

**Comment by xiahan4956** [comment]
手动捂脸

最近用您的插件很频繁,感觉很好用
我常常把它一直打开在后台.
有时候我会和身边的人对话,对话会录入到chatgpt的输入框中.
如果能够说"清空文本",可以清空输入框的内容,然后再说给chatgpt实际的指令,这样会很方便.

谢了老兄

**Comment by C-Nedelcu** [comment]
谢谢你的建议，这是一个好主意。我可以考虑在未来版本中添加这个功能。我已经计划很快推出一项新功能，它可以通过语音命令暂停对话，同时继续监听麦克风，并通过另一个语音命令恢复对话。这样你就可以暂停对话，然后再次恢复对话，而无需进行任何键盘操作。这可能已经解决了你的问题。

**Comment by C-Nedelcu** [comment]
亲爱的朋友，我已经在Github上发布了2.2.0版本的扩展（它需要几天时间才会出现在Google Chrome网店）。这个新版本带来了改进的暂停功能，应该有助于解决你的问题。你说出暂停的关键词，然后麦克风将保持开启状态，但程序不会做任何事情，直到你再次说出暂停的关键词。

**Comment by xiahan4956** [comment]
已经看到并且使用了,感谢~
