### ISSUE TITLE
Only English voice on Android

### ISSUE THREAD

**Issue by amitev** [C-Nedelcu/talk-to-chatgpt#64]
Hi all, I have successfully added the extension on my Android phone (using the Kiwi browser, as Chrome doesn't support extensions), but whatever AI language I choose, I always get the English voice.

Idea if it can be adjusted?

**Comment by C-Nedelcu** [comment]
I am afraid I cannot provide support for this as I don't have an android phone.
As far as I know only Chrome Desktop and Edge Desktop support this extension.
If any other browsers do, it's coincidental and not much I can do for it.

However, if any developer wants to contribute to the project and make changes to the extension to allow it to work under Kiwi Browser, I'd be happy to approve the changes.
