### ISSUE TITLE
offer a totally free Text To speech, edge and google

### ISSUE THREAD

**Issue by joe12801** [C-Nedelcu/talk-to-chatgpt#65]
dont need to pay,all is free,you can access to this project
https://github.com/rany2/edge-tts
https://github.com/pndurette/gTTS

**Comment by C-Nedelcu** [comment]
thank you, however I don't think this is very helpful to my project
If you want the Edge voices you can use Edge, if you want the Chrome voice you can use Chrome.
However a lot of people have been requesting ElevenLabs integration so I'm looking into that.
