### ISSUE TITLE
Start box not showing up. 

### ISSUE THREAD

**Issue by ibuki3d** [C-Nedelcu/talk-to-chatgpt#67]
See title. Not sure where to go from here. I enabled the extension, logged onto the chatGPT home from the provided link, no start box.

**Comment by dlysid** [comment]
same here, My guess is that OpenAi changed something that disabled this extension

**Comment by ruanmeneguello** [comment]
Same here, I thought the same, feels like is OpenAi side, so the extension may have to be reviewed, I tried all troubleshooting the documentation had, and none was solved. Amazing extension by the way

**Comment by Crispin-SD** [comment]
I think this is OpenAI-related, as I had two other GPT plugins go offline simultaneously.

**Comment by Yon70** [comment]
Same here. I hope the problem is solved soon.

**Comment by Helenchooo** [comment]
I tried on Chrome and Microsoft Edge and cannot find the start button. What happened? Is this related to technical issue?

**Comment by C-Nedelcu** [comment]
Hello,

OpenAI have changed the ChatGPT URL from chat.openai.com/chat to chat.openai.com, as a result the extension in v2.0.0 and below no longer works. I have submitted v2.0.1 to the Google Play Store, which fixes the issue. V2.0.1 is currently pending review, should be available within the next few days. Meanwhile, you can download and install the extension manually through dev mode.

I am keeping this open until v2.0.1 is available on the play store.

**Comment by C-Nedelcu** [comment]
I have published V2.0.2, exclusively on GitHub just now, this version ensures that the Talk To ChatGPT box appears on the right pages (won't appear on the login page, but will appear on every page where there is a text area for conversing with ChatGPT)
