### ISSUE TITLE
Can not install Talk-to-ChatGPT Google Chrome extension

### ISSUE THREAD

**Issue by yenntkaopiz** [C-Nedelcu/talk-to-chatgpt#71]
I from Japan and try to download your extention but it seem be not found any more.
https://chrome.google.com/webstore/detail/talk-to-chatgpt/hodadfhfagpiemkeoliaelelfbboamlk
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/44561161/232206681-595dd32f-f771-4da4-ae86-eca2f7da1e05.png">

**Comment by MikesMoneyMachine** [comment]
he said in the read me you need to install manually while google play store approves the new 2.1.0 version or wait for google to approve in a few days. read the read.me

**Comment by C-Nedelcu** [comment]
Indeed, the latest update is still pending review on the Chrome web extenstion store.
Sadly the one pending review is v2.0.1, I wasn't able to submit v2.1 yet (with the new UI)
I have to wait until v2.0.1 is approved and only then I'll be able to upload v2.1.

Hence I recommend manual installation. You can follow the instructions given on the home page for manual installation.

**Comment by sukinmin** [comment]
> he said in the read me you need to install manually while google play store approves the new 2.1.0 version or wait for google to approve in a few days. read the read.me

Thank you for your answer. If you don't mind, could you explain how to install it manually? It's my first time using GitHub. I tried to do it myself, but it was difficult for me. I searched the internet and found out that I need to install Visual Studio. So, I downloaded Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.4. What should I do after that?

**Comment by C-Nedelcu** [comment]
> > he said in the read me you need to install manually while google play store approves the new 2.1.0 version or wait for google to approve in a few days. read the read.me
> 
> Thank you for your answer. If you don't mind, could you explain how to install it manually? It's my first time using GitHub. I tried to do it myself, but it was difficult for me. I searched the internet and found out that I need to install Visual Studio. So, I downloaded Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.4. What should I do after that?
> 
> > I found out how to install it by reading your 'how to install option 2' paragraph. now I can use 'talk to chatgpt v.2.0.1' thank you

if I understand correctly, you have successfully installed the latest version.
If anyone else has the same question, here is how you do it.

1. Download the .zip file here: https://github.com/C-Nedelcu/talk-to-chatgpt/raw/main/chrome-extension/chrome-extension.zip (this link will always point to the latest version)
2. Extract the .zip file in a folder somewhere
3. Follow this tutorial to install the extension in Chrome in dev mode: https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by sukinmin** [comment]
> > > he said in the read me you need to install manually while google play store approves the new 2.1.0 version or wait for google to approve in a few days. read the read.me
> > 
> > 
> > Thank you for your answer. If you don't mind, could you explain how to install it manually? It's my first time using GitHub. I tried to do it myself, but it was difficult for me. I searched the internet and found out that I need to install Visual Studio. So, I downloaded Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.4. What should I do after that?
> > > I found out how to install it by reading your 'how to install option 2' paragraph. now I can use 'talk to chatgpt v.2.0.1' thank you
> 
> if I understand correctly, you have successfully installed the latest version. If anyone else has the same question, here is how you do it.
> 
> 1. Download the .zip file here: https://github.com/C-Nedelcu/talk-to-chatgpt/raw/main/chrome-extension/chrome-extension.zip (this link will always point to the latest version)
> 2. Extract the .zip file in a folder somewhere
> 3. Follow this tutorial to install the extension in Chrome in dev mode: https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

yes, I did it! :) thanks a lot
