### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by Happyme222** [C-Nedelcu/talk-to-chatgpt#73]
The zip seems to not have to images folder and gives an error on icon...

**Comment by Ranensol** [comment]
I had the same issue, I just grabbed the source code from the main page (click '<> Code', then 'Downalod as ZIP'), unzip it somewhere, then turn developer mode on in Chrome and point it at the 'chrome-extension' folder in the unzipped folder you created.

**Comment by Happyme222** [comment]
Ty Ranensol

**Comment by Ranensol** [comment]
No worries.

The zip link in the 'Readme.md' is for v2.1 and does seem to be missing the image files, but by the looks of it the guys here have been working around OpenAI changing their URL's (twice in as many days), so I reckon it's best endeavours.

I'm sure once it calms down it'll all be straightened out :)

**Comment by MithunPrabhu777** [comment]
Thank you Ranensol.

It is working fine for me.

**Comment by pixelsoda** [comment]
I got it to install, thank you Ranensol. The program works and looks great!

**Comment by C-Nedelcu** [comment]
I forgot to include the images in the zip file (for updates, the images aren't required, so Edge/Chrome stores never complain about the images being missing)

I repackaged the zip to include the images now, should be OK. I'm going to mark this as solved.
Sorry for the inconvenience!
