### ISSUE TITLE
ple add function google  tts  thans

### ISSUE THREAD

**Issue by wavelet2008** [C-Nedelcu/talk-to-chatgpt#74]
function CN_SayOutLoudvv(text) {
  const baseUrl = "https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob";
  const language = "en-US";
  gender = "male", speed = 1.1
  const encodedText = encodeURIComponent(text);
  const url = `${baseUrl}&tl=${language}&q=${encodedText}&gender=${gender}&ttsspeed=${speed}`;

  const audio = new Audio(url);
  audio.play();
}

**Comment by C-Nedelcu** [comment]
Why would you want this? Aren't the current Chrome/Edge text-to-speech voices not good enough?

PS: you can reply in your own language if you want. I will translate with ChatGPT.

**Comment by wavelet2008** [comment]
> Why would you want this? Aren't the current Chrome/Edge text-to-speech voices not good enough?
> 
> PS: you can reply in your own language if you want. I will translate with ChatGPT.

yes  Google's text-to-speech (TTS) technology offers a wide range of voice choices and produces high-quality voices with natural sounding speech, which could be some reasons why someone may prefer it over other TTS solutions.

**Comment by C-Nedelcu** [comment]
Google's text to speech is already integrated in the Chrome extension. I'm afraid I simply do not understand your request... but you might be interested to hear that I am looking into integration with ElevenLabs which will give apparently the best possible TTS there is. Almost everyone is asking for this.

**Comment by C-Nedelcu** [comment]
Hello there,

I have added ElevenLabs API support in v2.6.0.

This version has not been submitted to the Chrome/edge stores yet, I think it would need some beta testing first.
Would anyone please give it a try?

You have to install the new version manually, instructions are given on the project's home page.

**Comment by C-Nedelcu** [comment]
closed due to inactivity.
Feel free to reopen later if necessary
