### ISSUE TITLE
Waiting for slow talkers

### ISSUE THREAD

**Issue by TheTrueObelus** [C-Nedelcu/talk-to-chatgpt#76]
Hi, I've noticed while using the extension I have to speak quite quickly or it believes I've finished my sentence and responds, cutting me off. It would be useful if it would wait and listen a moment longer before responding. It would be even better if some option was available to set how long it would wait to hear a full voice input before responding. I can imagine this would be very useful for people with certain disabilities. Also I want to second the other requests for the integration of Eleven Labs custom voices or something like it. Thank you

**Comment by C-Nedelcu** [comment]
Hello there,
I recommend using the manual sending mode + using a send word. 
That way, you can take as long as you want. And when you're ready to send, speak the send word.
