### ISSUE TITLE
Stopped reading text after edit #Bug

### ISSUE THREAD

**Issue by bartman081523** [C-Nedelcu/talk-to-chatgpt#78]
Replicate bug:

Press the edit button on a users message, press "Save".
The message that is generated after the edit is not read anymore.

Desired behaviour:

Generated text after edit could also be read.

**Comment by C-Nedelcu** [comment]
interesting, I actually didn't know there was an edit button.
I can confirm the bug.

**Comment by chintan-1** [comment]
Hi @C-Nedelcu, I have just started learning Javascript but I would work upon resolving this bug.
can you please assign it to me.

**Comment by bartman081523** [comment]
@chintan-1 can you create a PR?

**Comment by C-Nedelcu** [comment]
> Hi @C-Nedelcu, I have just started learning Javascript but I would work upon resolving this bug. can you please assign it to me.

hello, it would be my pleasure if you can find a fix.
I am assigning you the issue. When you figure it out, you can make a pull request indeed.

**Comment by chintan-1** [comment]
Thank you!!
Sure, will create PR upon fix.

**Comment by C-Nedelcu** [comment]
Please note I am currently working on ElevenLabs integration right at this moment.
Hoping to make a commit & push in a moment.
If anyone is reading this and would be willing to test, I'd be delighted.

**Comment by bartman081523** [comment]
@C-Nedelcu 
> If anyone is reading this and would be willing to test, I'd be delighted.

I have tested ElevenLabs "Rachel Multi-Language" TTS voice, from your newest commit, and it is working fine (for me).
