### ISSUE TITLE
I absolutely love your app! - suggestion: A draggable UI element

### ISSUE THREAD

**Issue by JamaicanPoet20** [C-Nedelcu/talk-to-chatgpt#79]
Hi, 
First of all, thx for all your work. It literally made me love my work now :) .
A small suggestion. Do you think you could make your UI move around the screen?
I am an absolute beginner in python, but I think Tkinter library has Canvas.move() option?

It would make your extension absolute perfection in my eyes. Well maybe besides adding more languages, voice etc...

Thx again for your work!
Best,
Pete

**Comment by C-Nedelcu** [comment]
hi Pete,
I'm happy to get positive messages such as yours (the 1-star reviews on the chrome store are getting old)
Yes, having the possibility to move the widget around is an upcoming feature definitely!
I'll tag your suggestion as work in progress
Cheers!

**Comment by C-Nedelcu** [comment]
this has been implemented in v2.4 :)

**Comment by JamaicanPoet20** [comment]
I seriously appreciate it! I love it already!
