### ISSUE TITLE
Alert tone when paused by voice command

### ISSUE THREAD

**Issue by guit4eva** [C-Nedelcu/talk-to-chatgpt#83]
Sorry, one more suggestion quick :) When you use the pause command, a tone plays when it unpauses - which is great because you then know the pause command was successful. It would be amazing to have this tone for when it pauses as well, otherwise you need to physically check if it has actually paused or not.

**Comment by C-Nedelcu** [comment]
good idea! 

currently if you unpause, the word "OK" is spoken.
however I think it might get a bit old if "OK" is spoken every time you pause/unpause.

wondering what other sound I could use, something that works in every language... maybe a good old beep sound instead?

**Comment by guit4eva** [comment]
Yea, I think just a general beep would be better. Maybe just something short and sweet like this:

https://freesound.org/people/BeezleFM/sounds/512135/
https://freesound.org/people/plasterbrain/sounds/419493/
https://freesound.org/people/RICHERlandTV/sounds/351556/
https://freesound.org/people/plasterbrain/sounds/419493/

Maybe also a good idea to have one for pause and one for unpause. Then you are always 100% sure what it is doing without looking at your screen. What do you think?

**Comment by C-Nedelcu** [comment]
Yes that sounds good. I'll pick two of these sounds.

**Comment by guit4eva** [comment]
Awesome :) On the note of tones, might also be a good idea to have a tone after the "Manual send word(s)" command. Due to the delay in TTS after issuing a voice command, it's not always easy to know if your "Manual send word(s)" was successful or not

**Comment by C-Nedelcu** [comment]
This has been implemented in v2.5.0 :) 
Should be up on the extension stores by the end of the week.

**Comment by guit4eva** [comment]
That is awesome news, well done! 🙂🙂

**Comment by C-Nedelcu** [comment]
> That is awesome news, well done! 🙂🙂

this just went live on the Chrome store.
if you force-update the extensions, you should be getting v2.5.0 now
