### ISSUE TITLE
Suggestion: Add an optional "wake word", similar to how you do when you want to talk to Alexa

### ISSUE THREAD

**Issue by khirasaki** [C-Nedelcu/talk-to-chatgpt#84]
I'd love to have a "wake word" for ChatGPT to start listening to me, and then after I submit, to not start taking dictation again until I have said the wake word again.

This would be similar to how you talk to "Alexa" or "Hey, Google" to start off each interaction with them.

**Comment by C-Nedelcu** [comment]
Have you tried interacting with the pause words?
You can pretty much achieve this by saying "pause" (or whichever word you want) after you receive the response from ChatGPT.

**Comment by C-Nedelcu** [comment]
closed due to inactivity.
Feel free to reopen later if necessary
