### ISSUE TITLE
Could you please add norwegian voice

### ISSUE THREAD

**Issue by andersnicolai** [C-Nedelcu/talk-to-chatgpt#85]
I know that Edge has some great voices you can use when reading out loud, if you find a way to extract those voices I know that there are great Norwegian voices available there. 
Thank you for this extension

Okay

**Comment by C-Nedelcu** [comment]
hello anders, 
you can use the extension in Edge if you want, it's available on there too.
for additional voices we should be adding elevenlabs support which is a third party API that will offer many more voices in many languages.
