### ISSUE TITLE
Error When Selecting Language and Speech

### ISSUE THREAD

**Issue by liamtimms** [C-Nedelcu/talk-to-chatgpt#97]
Hi I am trying to get this working with `English - en-US` as my language but whether I use the default or the ElevenLabs option I receive a popup saying:

`Invalid settings values. TypeError: Cannot read properties of undefined (reading 'lang')`

when attempting to save the setting.

**Comment by pyjterq** [comment]
Same problem here.

**Comment by liamtimms** [comment]
@pyjterq  it was resolved for me by using Chrome itself rather than Chromium.

**Comment by C-Nedelcu** [comment]
Hello there,

Chromium does not support voice recognition, which effectively blocks support for this extension.

Sources:
https://groups.google.com/a/chromium.org/g/chromium-discuss/c/GqLtpyvXkik
https://stackoverflow.com/questions/64597174/speechrecognition-not-listening-on-chromium

**Comment by C-Nedelcu** [comment]
I'd like to state that many users are requesting for support of OpenAI Whisper API which is basically an alternative to the browser's speech recognition API. If I implement it, then de facto support for Chromium will be possible. 

A major drawback for the current version of Talk-to-ChatGPT is that it's reliant on web browser APIs for speech recognition and text-to-speech.

For text-to-speech, I've integrated ElevenLabs support.
Now, if I can integrate Whipser, then we won't need anything from the browser. 

Which means the extension will be browser-agnostic, possibily even opening the door for mobile usage.

**Comment by pyjterq** [comment]
> @pyjterq it was resolved for me by using Chrome itself rather than Chromium.

I see. I'm using Brave right now. I'll try Chrome instead.
