### ISSUE TITLE
interruption 

### ISSUE THREAD

**Issue by RAIJIN004** [C-Nedelcu/talk-to-chatgpt#98]
Aparte de utilizar una opcion como los auriculares, para las personas que no tengan podrias hacer que respondan a una serie de preguntas para que pueda familiarizarse con la persona y asi diferenciar cuando esa persona interrumpe la conversacion y asi deje de hablar y escuche denuevo, no se solo es una idea no se mucho del tema pero podrias hacer que se respondan unas preguntas personalizadas o algo por el estilo

**Comment by C-Nedelcu** [comment]
Hello,

Unfortunately everything about speech recognition is handled by the web browser APIs and I have absolutely no way of changing that. The idea you are suggesting is simply not possible for a project of this scope and nature.

This would only be possible if I had programmed the speech recognition functionality myself.
Or, if an external API for speech recognition could be used and would support what you are saying. I don't know any that does this. But if you ever find one, let me know and I can study if this can be integrated.

Thanks for your suggestions though!
:)
